### PR TITLE
Removed geolocation

### PR DESCRIPTION
**Pull request by mistergone**
This commit will remove geolocation for the time being.

It also has a change to the analytics file that is relatively minor.

### CODE REVIEW

**Comment by stephanieosan** [comment]
@akiany @ascott1 @contolini Anyone available to review and merge?

**Comment by OrlandoSoto** [comment]
@stephanieosan  @mistergone I think they all went out to lunch with the new fellows,, I can merge it but I noticed that Travis CI failed?

**Comment by stephanieosan** [comment]
@OrlandoSoto I think @mistergone also went out to lunch, so maybe we should just wait until they all get back.

**Comment by OrlandoSoto** [comment]
@stephanieosan ok

**Comment by mistergone** [comment]
The Travis failure is a problem with npm install, which is running fine locally. I think it might've been a temporary glitch... maybe? :dancer: :rocket:

**Comment by OrlandoSoto** [comment]
@mistergone ok!

**Pull request merged**
