### PR TITLE
Fix link label

### PR DESCRIPTION
**Pull request by dpford**
This updates the template to point to the newer link format.

Review: @kurtw @amymok

### CODE REVIEW

**Comment by amymok** [comment]
Looks good to me!!

**Comment by amymok** [comment]
Screenshot for reference:
screen shot 2015-06-16 at 1 14 51 pm

**Comment by amymok** [comment]
@stephanieosan @cfarm @virginiacc @fna

**Comment by stephanieosan** [comment]
:+1: Looks good! Let's do it!

**Pull request merged**
