### PR TITLE
Initial React refactor

### PR DESCRIPTION
**Pull request by virginiacc**
### Changes
- Add react & flux
- JS refactor
- Input table html/css refactor

### Notes
- Mobile functionality needs to be restored
- CSS updates/refactor needed

### Review
@cfarm

### CODE REVIEW

**Comment by cfarm** [comment]
:+1: lookin good. do we want to merge this before or after #432? i have no preference

**Comment by ascott1** [comment]
If y'all refactor the rate-checker to use React, can I help? Pretty please?

**Comment by amymok** [comment]
@ascott1 maybe we can also pair :) i need help with React, so confused :)

**Comment by cfarm** [comment]
@ascott1 I don't think that's on our radar butttt you can help us with LC :)

**Comment by ascott1** [comment]
> @ascott1 maybe we can also pair :) i need help with React, so confused :)

Sounds fun! I'd love to

> @ascott1 I don't think that's on our radar butttt you can help us with LC :)

 :metal:

**Pull request merged**
