### PR TITLE
fix trailing slash to match the front end

### PR DESCRIPTION
**Pull request by cfarm**
This should fix current failing browser test on dev site

you can run 

`behave -k features/loan_fha.feature -t=~prod_only`

to test but it will still fail locally because of the URL structure, but should work on dev site.

### CODE REVIEW

**Comment by cfarm** [comment]
@OrlandoSoto please review

**Comment by OrlandoSoto** [comment]
this is weird, when I manually navigate to loan options from my mac I get the trailing /

http://build.consumerfinance.gov/owning-a-home/loan-options/
and
http://www.consumerfinance.gov/owning-a-home/loan-options/

**Comment by cfarm** [comment]
me too. ¯\_(ツ)_/¯

**Comment by OrlandoSoto** [comment]
hmm so now if we take out the "/" it fails against build :(

**Comment by OrlandoSoto** [comment]
I have an idea why this build failed with url's don't match
http://zusa.demo.cfpb.gov/view/OAH/job/OaH-build.cf.gov-browser-tests/274/

**Comment by OrlandoSoto** [comment]
Here's my theory:
- The test navigated to http://build.consumerfinance.gov/owning-a-home/loan-options/FHA-loans/
- It clicked on "Understand loan options" which has "href="/owning-a-home/loan-options"
- The failure snapshot shows "Bad gateway - connection error - connection reset by peer"
- The browser address bar was probably stuck on "http://build.consumerfinance.gov/owning-a-home/loan-options'" as directed by the href value so the test failed
- The page never redirected to "http://build.consumerfinance.gov/owning-a-home/loan-options/"

**Comment by OrlandoSoto** [comment]
image

**Comment by OrlandoSoto** [comment]
but then there's also a chance that I'm losing my mind here :)

**Comment by cfarm** [comment]
@OrlandoSoto so this fix is not needed, then?

**Comment by OrlandoSoto** [comment]
@cfarm correct!

**Pull request closed without merging**
