### PR TITLE
switch templates to using static() function where possible

### PR DESCRIPTION
**Pull request by rosskarchner**
This helps better take advantage of some bandwidth-saving measures we're putting in place, see: https://github.com/cfpb/cfgov-refresh/pull/2407

### CODE REVIEW

**Comment by KimberlyMunoz** [comment]
I have a question, should LESS files and React.JS files also be adjusted?

There's L136 of `cf-theme-overrides.less`
 `@grid_box-sizing-polyfill-path: '/static/vendor/box-sizing-polyfill';`

And a react file at `/src/static/js/modules/loan-comparison/components/scenario-section.js`
``

Also, the index file of Owning A Home uses its own static function. Should that be updated?
`Illustration of house keys`

**Comment by rosskarchner** [comment]
- It seems like the preprocessor does the right thing for absolute references under /static/, but ideally react and less files would use relative paths (relative to the *built* location of the file)

That url function already does the right thing, though switching it to the static() function would be more explicit and less dependent on sheerlike "magic".

**Comment by KimberlyMunoz** [comment]
:+1:

**Comment by rosskarchner** [comment]
hmm, seems like something went crazy on that rebase

**Comment by rosskarchner** [comment]
Let's try again...

**Pull request merged**
