### PR TITLE
Landing page sidebar updates

### PR DESCRIPTION
**Pull request by stephanieosan**
#### Added
* Multiple categories of links to the sidebar
* New links and copy coming from /mortgages page
* Document download icon to PDFs (since the PDF icon has been deemed not-accessible)

#### Removed
* Arrows from links in sidebar—they were giving them too much emphasis, and arrows on links is an unresolved issue right now (rules aren't totally defined, some people arguing for no arrows at all, some for using to create emphasis)

#### Changed
* Description for "Know the process" to @mthibos' latest update

#### Screenshots
screen shot 2015-06-23 at 4 06 14 pm
screen shot 2015-06-23 at 4 06 24 pm

#### Notes
* One weird thing I noticed was that the links in the middle of the page are Regular, and the links in the sidebar are Medium. I think we'd want the links in the middle of the page to also be Medium. (Similarly to the arrows issue, the font weight of links is not totally resolved yet. It seems like the decision will end up being Regular for links in paragraphs, Medium for links outside of paragraphs, but that hasn't been stamped as a "final" decision yet, and hasn't been incorporated into the design manual or capital framework.)
* Other weird thing: **Lack of space between download icon and link text in main body.** I don't know why this is happening in the main body of the page, but not in that sidebar link. Dev help appreciated. 

#### Review
@sonnakim for link accuracy + copy
@virginiacc or @cfarm

### CODE REVIEW

**Comment by sonnakim** [comment]
I don't think I can review these. I can only access build right now. My dev environment's not ready for prime time!

**Comment by stephanieosan** [comment]
Okay! Maybe you can double-check the copy in the screenshots, then check the actual links once they're merged on build?

**Comment by sonnakim** [comment]
#### One copy tweak
For the fifth link, can we make it "the CFPB"?
"Learn how *the* CFPB is protecting mortgage borrowers"

#### One formatting tweak
In the resources section, can we include a line break before each link?

|  With line breaks (yay!)  |  Without (boo)  |
|---------------|-----------------|
|image|image|

**Comment by cfarm** [comment]
@stephanieosan The links that are Medium weight are [jump-links](https://cfpb.github.io/cf-typography/docs/) which makes them easier to tap on touch and small screens. 

Can you include some small and medium screen width screenshots too?

**Comment by stephanieosan** [comment]
Incorporated your feedback, @sonnakim! 

#### Mobile screenshots
screen shot 2015-06-24 at 10 52 44 am
screen shot 2015-06-24 at 10 52 51 am
screen shot 2015-06-24 at 10 53 04 am
We probably want those "Key tools" links to be jump links so that they have the appropriate mobile style. Do I just add that class? Are there any classes I need to remove?

#### Medium, tablet-ish screenshots
screen shot 2015-06-24 at 10 54 37 am
screen shot 2015-06-24 at 10 54 43 am

**Comment by sonnakim** [comment]
Sweet—thanks @stephanieosan!

**Comment by cfarm** [comment]
These link changes will also require updating the browser tests, FYI - let me know if you want help with that.

**Comment by stephanieosan** [comment]
Yes, I definitely don't know how to do that yet!

**Comment by stephanieosan** [comment]
Okay, so I fixed the weird download icon spacing issue with well-placed nonbreaking spaces. I turned all of the main body links into jump links so that they'd be Medium instead of Regular weight and be more mobile-friendly.

Still working on updating the browser tests, but in the mean time...I found another css issue.

Our lists of links were looking pretty janky on mobile:

What they look like (boo) | What want them to look like (yay!)
---- | ----
screen shot 2015-06-24 at 5 26 20 pm  | screen shot 2015-06-24 at 5 26 55 pm

So, I realized list_link is there to make your lists of links stack nicely on mobile, but it's not activated unless you have list__links as a class for your ul. Which, is easy enough to do, but that also happens to affect the way the links look on desktop, making the spacing too tight.

What they currently look like (yay!) | What they'd look like if I added list__links (boo)
---- | ----
screen shot 2015-06-24 at 5 33 53 pm | screen shot 2015-06-24 at 5 27 12 pm


Should we make some kind of css override so that we can get the nice mobile list properties without the too-tight desktop spacing?

**Comment by mthibos** [comment]
@stephanieosan  you are turning into such a developer!

Also, for my knowledge, what do y'all mean by "jumplinks"?  Because you don't seem to mean /#something, which is the only definition I know for the term.

**Comment by stephanieosan** [comment]
Yes, the terminology is confusing in this case. 

"jump-link" is what the flapjack devs have named one of the common css classes for links. That class creates a fancy mobile link with dotted lines above and below.  

The thing you know as "jumplink" (/#something) should probably be referred to as "anchor link", to ease confusion.

(Apparently this mix-up is why everyone was giving you blank stares in sprint planning earlier!)

**Comment by stephanieosan** [comment]
Also, note to self: we are still missing the URL for the realtors pages, so I will need to:
- [ ] Add link and updated corresponding browser test

Once we hear back from the Design Ops crew. Thanks for emailing them, @sonnakim !

**Comment by mthibos** [comment]
@stephanieosan 

Well that is mighty confusing of the flapjack devs, isn't it.  :confounded:

**Comment by stephanieosan** [comment]
I've removed the realtors link for now, as discussed in scrum, and updated the browser tests accordingly. This is ready for review!

**Comment by amymok** [comment]
Travis build failed because of this commit https://github.com/amymok/owning-a-home/commit/35746b43b622b5e38ae4ab01f0d93b3a45b8f1f4

As noted, all tests passed.

Everything should be fine after https://github.com/cfpb/owning-a-home/pull/490 is merged in.

**Comment by virginiacc** [comment]
@stephanieosan I think for the link spacing issue we could add a rule so that when you use `.list__links` and `.list__spaced` together, the list items get the increased margin value on desktop. 

It looks like there's already an entry for `.list__links.list__spaced` in the `index.less` file -- we can add this list_item rule to it:

```
.list__links.list__spaced {
  .list_item {
      .respond-to-min(@tablet-min, {
        margin-bottom: unit(24px / @base-font-size-px, em)
      });
  }
}
```

**Comment by stephanieosan** [comment]
Okay, I updated the less file and added all the appropriate classes. Check it out!

**Comment by virginiacc** [comment]
Looks awesome! :+1:

**Pull request merged**
