### PR TITLE
Smoke Tests

### PR DESCRIPTION
**Pull request by amymok**
Update smoke tests

## Additions

- Added smoke tests for closing disclosure + loan estimate

## Removals

- Deleted Good Faith Estimate link check

## Review

- @fna @virginiacc @OrlandoSoto 
Anything else we should add to smoke tests?

## Checklist

* [X] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices 
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by OrlandoSoto** [comment]
I would not tag 404 tests as smoke tests, that way those 404 tests only execute when the nightly regression tests are run. 
The smoke tests are primarily used to verify that the page has loaded without crashing and it's stable enough to perform the more exhaustive/regression tests

**Comment by OrlandoSoto** [comment]
The word "closing" is misspelled in line 1 of closing_disclosure.feature
Feature: Test the default values in the Clsoing Disclosure page

**Comment by OrlandoSoto** [comment]
BTW: it's great to see a good amount of test coverage in this page,, nice work OaH friends!

**Comment by amymok** [comment]
@OrlandoSoto I changed what I added as smoke test for closing disclosure and loan estimate.  Now they are not those 404 link tests, but the test that check if tabs were on the page. (I didn't try to benchmark them though, but think they may be pretty fast :) )

**Comment by OrlandoSoto** [comment]
:+1: thanks @amymok !

**Comment by virginiacc** [comment]
This looks great! :+1:

**Pull request merged**
