### PR TITLE
Form explainer release

### PR DESCRIPTION
**Pull request by cfarm**
Adds all form-explainer related features, files, dependencies, tests. Branched off the latest released version of the repo in `hotfix-latest`

## Additions

- form explainer templates, js, css, images
- project dependency updates for compiling, and running unit tests
- js unit tests for check-rates code that hasn't been deployed previously
- js unit tests for form explainers
- browser tests for form explainers

## Testing

- checkout locally
- run `frontendbuild.sh` to run js tests and install dependencies and whatnot
- run the following browser tests:
```
behave -k features/loan_estimate.feature
behave -k features/closing_disclosure.feature
```

## Review
Please checkout locally to review/QA! Issues can be logged in GHE#1049

- @virginiacc 
- @stephanieosan 
- @sonnakim 
- @amymok 
- @huetingj 

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* ~~Code can be automatically merged (no conflicts)~~ lol
* [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Passes all existing automated tests
* [x] New functions include new tests
* [x] New functions are documented (with a description, list of inputs, and expected output)
* [x] Placeholder code is flagged
* [x] Visually tested in supported browsers and devices 
* [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by cfarm** [comment]
The Travis build is failing and I don't know whyyyy https://travis-ci.org/cfpb/owning-a-home/builds

We can still carry on with QA on local machines anywho.

**Comment by contolini** [comment]
Try changing:
```
  - npm install -g grunt-cli
  - ./frontendbuild.sh
```
to
```
  - npm install -g grunt-cli
  - chmod +x frontendbuild.sh
  - ./frontendbuild.sh
```
in https://github.com/cfpb/owning-a-home/blob/master/.travis.yml#L6-L7

**Comment by cfarm** [comment]
@virginiacc here's the failing test for this branch: https://travis-ci.org/cfpb/owning-a-home/builds/74253123
to replicate local, delete the node_modules folder and re-run frontendbuild.sh

**Comment by amymok** [comment]
@cfarm This is now at least passing travis, but there are a lot of differences in terms of packages we use and others that were in the original master that were not carried over here.  Is that okay?

**Comment by cfarm** [comment]
@amymok definitely ok and expected, since this branch does not require a lot of things we use on master . Awesome that this is working now!

**Pull request closed without merging**
