### PR TITLE
Updates readme and fixes error

### PR DESCRIPTION
**Pull request by anselmbradford**
- Updates readme to show how to copy config file from the command line.
- Fixes error in config instructions where wrong line number and
formatting were given.
- Capitalizes `url`.

### CODE REVIEW

**Comment by mthibos** [comment]
Ain't nothing like a new user to find all the holes in our readme.  Thanks for cleaning up @anselmbradford !

**Comment by ascott1** [comment]
@anselmbradford The configs now live in a `json` file rather than a javascript one. Mind updating that while you're at it?!

Thanks!

**Comment by anselmbradford** [comment]
@ascott1 Ready for review! Thanks!

**Comment by mistergone** [comment]
selfie-0

**Comment by fna** [comment]
@ascott1 will the fact that configs are in json format require us to change Jenkins where we actually set the values for the APIs?

**Comment by anselmbradford** [comment]
Oops, missed `.js` > `.json` file extension fix here. Fixed in https://github.com/cfpb/owning-a-home/pull/318

**Comment by ascott1** [comment]
@fna I think all of the configs have been changed with jenkins?

**Pull request merged**
