### PR TITLE
Styling tweaks, dots to overlays, filter tabs, pagination, fixes img path.

### PR DESCRIPTION
**Pull request by himedlooff**

### CODE REVIEW

**Comment by himedlooff** [comment]
@ascott1 or @contolini, mind reviewing?

**Comment by himedlooff** [comment]
Tests are passing! yay!
selfie-0

**Comment by ascott1** [comment]
selfie-0

**Comment by ascott1** [comment]
Realize that my gif was not very descriptive... there's a lot here, but the code looks really solid. Excited to see this in action.

**Comment by himedlooff** [comment]
Gracias!

**Comment by mthibos** [comment]
@himedlooff , when I scroll down, the dummy page 2 appears and scrolls up to replace the page 1.  is that supposed to happen?

**Comment by himedlooff** [comment]
There is definitely a weird bug. Sometimes when I load the page and click "next" on the pagination it doesn't show me page 2. I have a fix locally, will make a pr and see if that fixes your issue as well.

**Pull request merged**
