### PR TITLE
Form explainer changes

### PR DESCRIPTION
**Pull request by virginiacc**
### Changes
- Remove `all` tab and `alert` category
- Restyle tabs

### Screenshots
screen shot 2015-06-24 at 2 05 30 pm

### Review
@cfarm @stephanieosan @huetingj 

### Notes
- Discussion in GHE issue 994
- I also added functionality to handle image size updates on window resize, but I've pulled that out to a separate branch so this one's easier to review. Separate PR to follow.

### CODE REVIEW

**Comment by cfarm** [comment]
Just to confirm the new URLs, these are what I'm looking at locally:

* http://localhost:7000/loan-estimate/
* http://localhost:7000/closing-disclosure/

**Comment by cfarm** [comment]
When I first load the page, neither of the tabs is active and it looks a little weird. Can Checklist be selected by default?

screen shot 2015-06-24 at 3 16 42 pm

**Comment by virginiacc** [comment]
@cfarm Yes, those should be the new URLs. I also just pushed a fix for the initial active tab. Thanks!

**Comment by cfarm** [comment]
Another design thing:

When you hover over a highlighted block, the explainers position to the left more to indicate the association:

screen shot 2015-06-24 at 3 40 56 pm

If you select it, though, and hover off it, it does a weird animation to the normal position. It only is tied to the hover event. I would recommend:

* When you hover, it bumps to the left
* When you click and select it, it is also bumped to the left
* Unclick it, or click another tool, and it unbumps
* Hovering over another explainer box bumps the hovered element to the left, while the selected element is still also bumped

@stephanieosan @huetingj @sonnakim thoughts?

**Comment by cfarm** [comment]
Also, this is not necessary for this PR to merge

**Comment by cfarm** [comment]
For screen sizes smaller than 800px, the definitions/checklist headings in the tabs are hidden. These could be refactored so that they are visible for screen sizes 332pixels and up.

## Current tablet view
screen shot 2015-06-24 at 3 46 15 pm


## Recommended mobile view at 332pixels wide when the headings fit in the tabs
screen shot 2015-06-24 at 3 46 50 pm

**Comment by stephanieosan** [comment]
Agreed with @cfarm's recommendation to add back in the tab titles "checklist" and "definitions" on smaller screens!

Maybe the hover weirdness you found could get added to the hover state recommendation @sonnakim has been working on (it's one of the issues that got moved to the backlog out of this sprint). That way we can give it a little more design thought, too.

**Comment by cfarm** [comment]
Let's merge this for now and the mobile tab headings can be added via future PR!

**Comment by stephanieosan** [comment]
:+1: :boom: :quokka: <<<where is the emoji for quokka?

**Comment by mthibos** [comment]
Huzzah!!  I can see the changes on build, at the right URLs.  Yay!  :+1:  

Agree, so sad, :cry: that there is no emoji for :quokka:

**Comment by mthibos** [comment]
However, on the loan-estimate page, I think the merging of the checklist + alert categories failed somehow.  I am only seeing the former checklist category, not the former alert category.  On /closing-disclosure, it is working.

@cfarm or @virginiacc can you investigate and restore the missing content?

**Comment by Scotchester** [comment]
What on earth is "quokka"?

**Comment by sonnakim** [comment]
@Scotchester https://github.cfpb.gov/OAH/OAH-notes/issues/1010

**Comment by sonnakim** [comment]
Every sprint, one team member designates an OaH mascot. This sprint @virginiacc has appointed the adorable yet deadly quokka. Quokka!

**Comment by Scotchester** [comment]
Ahah :)

**Pull request merged**
