### PR TITLE
Form explainer: new messaging

### PR DESCRIPTION
**Pull request by virginiacc**
### Changes
- updates messaging when there are no terms of a given type for a page
- calls form explainer code from separate files for loan estimate/closing disclosure (this is a quick implementation, so we can consider improving it)

### Preview
screen shot 2015-07-28 at 11 42 17 am

screen shot 2015-07-28 at 11 42 39 am

### Review
@cfarm @stephanieosan

### CODE REVIEW

**Comment by stephanieosan** [comment]
@mthibos In your copy you didn't have the quotation marks, but I think it helps. Do you want them removed, or are you good with the copy as-is?

**Comment by mthibos** [comment]
I'm fine with quotes.  :+1:

**Comment by stephanieosan** [comment]
Excellent, looks good to me!

**Comment by cfarm** [comment]
@virginiacc this has conflicts now.

**Comment by virginiacc** [comment]
@cfarm The conflicts should be resolved now!

**Comment by cfarm** [comment]
:+1:

**Pull request merged**
