### PR TITLE
Remove maintain from landing page and navigation

### PR DESCRIPTION
**Pull request by amymok**
## Removes

* Remove maintain from landing page
* Remove maintain on top and bottom navigation

## Review

@virginiacc @cfarm @huetingj @stephanieosan 

## Screenshot

Landing Page:
screen shot 2015-06-02 at 1 01 04 pm
screen shot 2015-06-02 at 1 02 17 pm

Navigation:
screen shot 2015-06-02 at 12 57 34 pm
screen shot 2015-06-02 at 12 58 07 pm
screen shot 2015-06-02 at 1 01 43 pm
screen shot 2015-06-02 at 1 01 56 pm

### CODE REVIEW

**Comment by huetingj** [comment]
looks good to me!

**Comment by stephanieosan** [comment]
:+1:

**Comment by cfarm** [comment]
Looks great!

**Comment by cfarm** [comment]
Oops, we forgot to update the browser tests for this, so now build is failing. @amymok maybe you and I can fix this together tomorrow, it should only take a few minutes :)

**Pull request merged**
