### PR TITLE
Journey illos

### PR DESCRIPTION
**Pull request by cfarm**
## Added
* Illustrations for the landing page process steps
* Illustrations for individual Journey phase pages

## Changed
* Landing page whitespace in the phase info text columns was reduced to better match design comp

## Review
* @virginiacc 
* @stephanieosan 
* @huetingj 

screen shot 2015-03-30 at 6 02 47 pm
screen shot 2015-03-30 at 6 02 53 pm
screen shot 2015-03-30 at 6 03 01 pm
screen shot 2015-03-31 at 11 22 00 am

### CODE REVIEW

**Comment by huetingj** [comment]
These look snazzy! It looks like the "Prepare to shop" screenshot is of the old design. I'm wondering when the top nav is in and we lose that open top white space if it would make sense to push the illustration down a little to get it away form the top and more floating in the space next to the paragraph.

**Comment by stephanieosan** [comment]
Yeah, we could also do something like this, where we widen the line length of that intro paragraph and make the illustrations a little bigger (3 columns):
screen shot 2015-04-01 at 10 40 25 am
screen shot 2015-04-01 at 10 40 35 am

**Comment by huetingj** [comment]
Thanks for mocking it up--- that looks great!

**Comment by cfarm** [comment]
Once #396 gets merged I can bring those styles in here to match the latest design, thanks for the comp @stephanieosan!

I'll also need to update the variable here to use the `url` key instead of `slug` since that changed in #396

**Comment by virginiacc** [comment]
This looks great! :+1:  Is it ready to be merged?

**Comment by cfarm** [comment]
Not ready yet, still need to make design adjustments for the comp Stephanie posted.

**Comment by cfarm** [comment]
Just updated with:

* Larger images
* images are flush with the text container for 800px width screens and up
* columns are 3/4 and 1/4 for text and image
* Fixed broken compare page slug

screen shot 2015-04-02 at 3 51 40 pm
screen shot 2015-04-02 at 3 51 36 pm
screen shot 2015-04-02 at 3 51 31 pm
screen shot 2015-04-02 at 3 51 26 pm
screen shot 2015-04-02 at 3 51 19 pm

**Comment by virginiacc** [comment]
Looks good! The only issue I'm seeing is the phase image urls aren't working for me with the `base_url` segment. Although I'm wondering now if we should upload those images to WordPress and pull them in along with the rest of the phase content.

**Comment by huetingj** [comment]
:+1:  perfection

**Comment by cfarm** [comment]
@virginiacc to get relative URL images working locally I usually have to change the `base_url` to `/` - @ascott1 can you confirm the `base_url` paths here should work on build? https://github.com/cfpb/owning-a-home/pull/397/files#diff-1725730cb85c15ca748ae53951168c1dR45

**Comment by virginiacc** [comment]
@cfarm I think we can go ahead and merge this. I'm leaning towards moving the phase images to WP, so we can look at that as a next step once these changes are in.

**Comment by cfarm** [comment]
WP makes sense for sure.

**Pull request merged**
