### PR TITLE
Remove Left Nav from Loan Options

### PR DESCRIPTION
**Pull request by amymok**
### Changes:
* Remove left navigation
* Added back link to Owning a Home home page
* Line up content with the back link

### Screenshots:
*Desktop*:
screen shot 2015-07-15 at 2 03 20 pm

*Medium-sized*:
screen shot 2015-07-15 at 2 03 35 pm

*Mobile*:
screen shot 2015-07-15 at 2 03 47 pm

### Reviews:
@stephanieosan @huetingj @cfarm @virginiacc

### CODE REVIEW

**Comment by sonnakim** [comment]
I'm really not a fan of having the content stretch full width, as the line lengths make the text difficult to read. But the only solution I can think of is to have a blank space on the right hand nav where the sidebar would go. That would look like this: 

image

@stephanieosan @huetingj what do you guys think? Also discussed here:

https://github.cfpb.gov/OAH/OAH-notes/issues/996#issuecomment-47446

**Comment by cfarm** [comment]
@sonnakim that looks good to me.

**Comment by stephanieosan** [comment]
Yeah, let's do that. :+1:

**Comment by amymok** [comment]
How about these? @sonnakim @stephanieosan @huetingj 

**Desktop**:
screen shot 2015-07-15 at 6 59 41 pm

**Medium-sized**:
screen shot 2015-07-15 at 6 59 54 pm

**Mobile**:
screen shot 2015-07-15 at 7 00 05 pm

**Comment by sonnakim** [comment]
:+1: Looks good!

**Comment by cfarm** [comment]
@amymok this broke the smoke tests, I forgot to mention here that you need to update the associated browser tests for this left nav now that it's gone.

**Comment by huetingj** [comment]
looks great!

**Pull request merged**
