### PR TITLE
updated behave version, improved debug message, mod for dp amount

### PR DESCRIPTION
**Pull request by OrlandoSoto**
- Updated to behave 1.2.5 for better output log info
- Updated debug messages in the browser tests
- Added some code to ensure our DP amount does not get overwritten by the API and causing our tests to fail

### CODE REVIEW

**Comment by cfarm** [comment]
@OrlandoSoto what behave command should I run for this?

**Comment by OrlandoSoto** [comment]
@cfarm run:
- behave -k features/rate_checker_loan_amount.feature 

The output log will show a debug message
- Actual downpayment percent is:

But I just noticed that the down payment percent field does not have a text attribute, so I will change the test to read the value attribute instead

**Comment by cfarm** [comment]
I had one failure for these:

Given I navigate to the "Rate Checker" page                                         # features/steps/steps_navigation.py:22 12.032s
      Assertion Failed: 
      Expected: 'Chart is loaded'
           but: was 'Chart is NOT loaded'

is that expected? I noticed when I manually navigate to the page locally the chart doesn't load right away

**Comment by cfarm** [comment]
I ran this a subsequent time and it did not fail on that step or any other.

**Comment by OrlandoSoto** [comment]
in steps_navigation.py, line 33 I used as a workaround:
- context.base.sleep(1)
which causes the test to wait 1 second for the chart to load.
For now we can probably increase the sleep command to 2 or 3 seconds but we should open up a task to optimize that area, otherwise the smoke tests will take longer to execute

**Comment by cfarm** [comment]
@OrlandoSoto do you want to add this change? If not we can leave it too. I haven't been able to replicate that failure since the first time.

**Comment by OrlandoSoto** [comment]
yes, please. That code will take a snapshot if the county field does not get highlighted. I will probably add more sections where we take a screenshot if the test fails, that way we get additional visibility into the failure.

**Comment by cfarm** [comment]
I meant your change you described but did not commit: "in steps_navigation.py, line 33 I used as a workaround:"

**Comment by OrlandoSoto** [comment]
@cfarm OK I bumped it up to 2 seconds,, I'm looking for a more robust way to do this though

**Comment by cfarm** [comment]
:+1: tests are passing consistently so let's do this

**Comment by cfarm** [comment]
@OrlandoSoto after you fix conflicts that is :)

**Comment by OrlandoSoto** [comment]
@cfarm ok, I fixed it

**Pull request merged**
