### PR TITLE
add sidebar link to landing page

### PR DESCRIPTION
**Pull request by cfarm**
I forgot to commit this change (but I documented it!) in my original PR #471 

Landing page sidebar

### CODE REVIEW

**Comment by stephanieosan** [comment]
I'm confused—where did the new sidebar link come from? Was it always there? What's going on?!

**Comment by mthibos** [comment]
Maybe we did this while you were gone?  It was a hotfix in response to external feedback.  It's been on production for several weeks now.

**Comment by cfarm** [comment]
Yep, it wasn't on master branch because it was pushed to production as a hotfix.

**Comment by cfarm** [comment]
self-merge to fix our failing browser test which is looking for this link :)

**Comment by stephanieosan** [comment]
Okay, cool! 

We're looking at the sidebar links today, and this wasn't on my list because I was looking at build instead of production when I made the list. I will add it to my list so it doesn't get lost when we're looking at new organizations for the sidebar links!

**Pull request merged**
