### PR TITLE
Test journey links

### PR DESCRIPTION
**Pull request by fna**
Checking that the main /process/XXX links are working and all links of the same form on each of those pages are working too.

### CODE REVIEW

**Comment by fna** [comment]
Now on local box tests will only check "local" links ( localhost/owning-a-home/process/XXX ), because there are links to /es, /hmda, etc which will return 404, so it would be a false positive. In other environments it will check all links. 

A status code of 2XX and 3XX is considered good. 3XX codes I need to not fail external services, like youtube which redirects to www.youtube.

**Comment by cfarm** [comment]
@amymok can you review this?

**Comment by amymok** [comment]
Tests ran locally with no errors.  Good to go!

**Comment by stephanieosan** [comment]
yay! merge?

**Pull request merged**
