### PR TITLE
updated API tests

### PR DESCRIPTION
**Pull request by OrlandoSoto**
We can probably cover this one too in the test handoff meeting

### CODE REVIEW

**Comment by cfarm** [comment]
How can I run the test locally?

**Comment by OrlandoSoto** [comment]
@cfarm in test/api_testing/features/environment.cfg 
set base_url = http://build.consumerfinance.gov/oah-api/rates/rate-checker

then from test/api_testing run behave -k

**Comment by cfarm** [comment]
Needed to do the following to test locally:

1. Create the config file 
2. Run `pip install requests` module
3. Run `behave -k -t=~prod_only` to omit production environment tests

 @OrlandoSoto Can you add these steps to the readme for this PR?

**Comment by OrlandoSoto** [comment]
@cfarm ok, I added a Readme file and also provided a sample .cfg file, similar to what we did for the browser tests

**Comment by cfarm** [comment]
Can you add the readme into the main repo readme after the browser tests instructions?

**Comment by OrlandoSoto** [comment]
@cfarm done! ^^^

**Pull request merged**
