### PR TITLE
Journey tool fixes & illustration move to WP

### PR DESCRIPTION
**Pull request by virginiacc**
### Changes
- Display tool text instead of url
- Correctly assign url to tool href attribute
- Show step description at full width when there is no key tool
- Move phase illustrations to WP

### Screenshots
screen shot 2015-04-09 at 7 22 34 pm

### Review
@cfarm 
@stephanieosan 
@sonnakim

### CODE REVIEW

**Comment by cfarm** [comment]
:shipit:

**Comment by cfarm** [comment]
@stephanieosan @sonnakim A design related comment: aren't the line lengths uncomfortably long for the steps that don't have a key tool when displayed this way? Readability is not so great (I recommend clicking on the screenshot for actual-size effect):

screen shot 2015-04-10 at 11 27 06 am

**Comment by cfarm** [comment]
What if the action steps column maintains the same width regardless of whether the Tools green sidebar is present? Like so:

screen shot 2015-04-10 at 11 29 13 am

The page will be taller but 1) people scroll and 2) they'll be better able to read the content with more usable line lengths.

**Comment by Scotchester** [comment]
Re: line lengths:

I've been meaning to add a universal max-width rule to paragraphs in cf-core for ages.

```css
p {
    max-width: 35em;
}
```

I suggest you try adding that to your project CSS and see how it looks.

**Comment by virginiacc** [comment]
Yeah, without the tools, those lines are pretty long. We could target the intro paragraphs and only make them full width when the phase tools are present:

screen shot 2015-04-10 at 1 08 18 pm


vs:

screen shot 2015-04-10 at 1 07 52 pm


Or, as @Scotchester suggests, set a universal max-width. That could help with the readability of the `How to take action` and `What to know` sections as well:

screen shot 2015-04-10 at 12 15 57 pm

@sosan @huetingj @sonnakim

**Comment by stephanieosan** [comment]
I'm good with either a universal max-width or Virginia's first suggestion.

**Comment by cfarm** [comment]
:+1: to universal max width.

**Comment by virginiacc** [comment]
Okay, I added the width restriction when there are no phase tools as a quick fix so we can get the other changes in this PR merged. We can address the universal max width in a separate pull request since we'll probably want to review it on the other oah pages.

**Comment by stephanieosan** [comment]
:+1:

**Comment by cfarm** [comment]
New changes look good to merge

**Pull request merged**
