### PR TITLE
Closing pdf link updates

### PR DESCRIPTION
**Pull request by stephanieosan**
### Changes
* Many links within our two PDFs didn't have "www" in them, so they weren't working. This is fixed now.
* Fixed the table of contents for the closing forms PDF so all links now work

### Review
@virginiacc or @amymok 
cc: @mthibos

### CODE REVIEW

**Comment by virginiacc** [comment]
Looks good! :+1:

**Comment by stephanieosan** [comment]
Ah, good catch! Sorry, I was in meetings and then at the doctor's. I will fix this right now.

If you've already deployed (or don't want to wait), that's fine. If not, fix coming soon!

**Comment by virginiacc** [comment]
@stephanieosan Awesome, thanks! We haven't deployed yet, so I think we can pull this in first...

**Comment by stephanieosan** [comment]
Okay, here we go!

**Comment by virginiacc** [comment]
:+1:

**Pull request merged**
