### PR TITLE
Make Show and Hide visible in Loan Comparison

### PR DESCRIPTION
**Pull request by amymok**
### Deletions
* Remove the class to hide show/hide text

### Screenshots
Designers @sonnakim @stephanieosan @huetingj Please advise how you want this to look.

Desktop:
screen shot 2015-07-16 at 5 23 39 pm

Medium-sized:
screen shot 2015-07-16 at 5 23 53 pm

Mobile:
screen shot 2015-07-16 at 5 24 42 pm

### Reviews:
@sonnakim @stephanieosan @huetingj

### CODE REVIEW

**Comment by stephanieosan** [comment]
I'd recommend adding a space at the end of "Show" and "hide" so there's a little separation between the plus/minus sign. 

I'd also recommend that we not display the words "Show" and "hide" on medium and small screens.

**Comment by huetingj** [comment]
I endorse this recommendation.

**Comment by sonnakim** [comment]
I agree we should add a space. 
I personally think if it's not too much trouble, it would be nice to have Show/Hide appear on mobile and medium: 

On mobile, we actually should have room to display the words "Show" and "Hide":
image

For medium screens, we'd have to move "Scenario A" and "Scenario B" columns as a unit as shown below. Would this be too much work to implement? 
image

**Comment by sonnakim** [comment]
(If it's too much work, I'm ok losing the labels for medium & mobile!)

**Comment by stephanieosan** [comment]
Also, what size is that Show/Hide copy, @amymok ? It looks big.

**Comment by amymok** [comment]
@stephanieosan font size is 22px

**Comment by amymok** [comment]
@sonnakim that sounds more complicated, @virginiacc @cfarm what do you think?

**Comment by amymok** [comment]
@sonnakim @stephanieosan @huetingj What do you think?

Desktop:
screen shot 2015-07-17 at 1 26 08 pm

Medium-sized:
screen shot 2015-07-17 at 1 26 29 pm
screen shot 2015-07-17 at 1 27 10 pm

Mobile:
screen shot 2015-07-17 at 1 26 49 pm

**Comment by sonnakim** [comment]
Whoo hoo! :+1:

**Comment by sonnakim** [comment]
(That was fast!)

**Comment by amymok** [comment]
yes, amazing @cfarm and @virginiacc, that's why :)

@cfarm @virginiacc this is ready for merging.

**Comment by amymok** [comment]
unless @stephanieosan @huetingj have more questions.

**Comment by stephanieosan** [comment]
Merge, merge, merge! :boom:

**Comment by virginiacc** [comment]
Looks good to me! :+1:

**Comment by huetingj** [comment]
:+1: :dancers: :dancer:

**Pull request merged**
