### PR TITLE
Rate Checker content updates

### PR DESCRIPTION
**Pull request by cfarm**
These are content changes to the current live version of the site, meaning the branch is way behind our development work on master. I based this branch off of @Scotchester's #384 hot fix branch.

## Changes
* Landing page heading copy for the Rate Checker
* Landing page gets a new link in the Related Links section
* Rate Checker page gets new heading
* Rate Checker introduction paragraph has copy and link updates
* Add browser tests for the new links
* Update homepage link browser test

## Review
* @virginiacc GHE#928 has the content changes for this

### CODE REVIEW

**Comment by virginiacc** [comment]
@cfarm I've run this locally and all the changes look great! :+1:

**Comment by cfarm** [comment]
@OrlandoSoto For browser tests, we won't be running tests tagged `loan_comparison` on build or content or production, right?

**Comment by OrlandoSoto** [comment]
@cfarm correct!

**Comment by OrlandoSoto** [comment]
also being that the changes are only content, I would say let's skip API tests and only run browser tests

**Comment by cfarm** [comment]
I added a new scenario to test the new landing page link. 

I didn't update any link tests for the Rate Checker - it looks like those introduction links are not currently tested, so I'll wrote a new scenario for those shortly.

**Comment by cfarm** [comment]
Ok, I added the last of updated test scenarios for this branch, this time for the Rate Checker page. @virginiacc can you try out the `navigation.feature` and `rate_checker_links.feature` tests to make sure they pass for you?

**Comment by virginiacc** [comment]
@cfarm The tests look good! The absolute url tests are passing, and the relative ones are failing in expected ways.

**Comment by OrlandoSoto** [comment]
Don't forget the change for the Dept. of Agriculture in features/loan_special.feature line 46
from:
-  | US Department of Agriculture          | rurdev.usda.gov/had-guaranteed_housing_loans.html                   | Guaranteed Housing Loans                          |
to:
+  | US Department of Agriculture          | http://www.rd.usda.gov/programs-services/single-family-housing-guaranteed-loan-program | Single Family Housing Guaranteed Loan Program |

**Comment by cfarm** [comment]
@OrlandoSoto thanks, just pushed that update.

**Pull request closed without merging**
