### PR TITLE
Scroll bug fix

### PR DESCRIPTION
**Pull request by virginiacc**
Fixes issue where closing step expandable using the 'hide' link at the end of expandable content scrolls user to bottom of page

## Changes

- Scroll to top of expandable when expandable is closed from bottom link

## Testing

- Check out branch
- Run `frontendbuild.sh`
- Navigate to one of the journey pages
- Open a step expandable and then close it from the bottom `hide` link
- Check that you have been scrolled to top of expandable when it's closed

## Review

- @cfarm 

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices 
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by mthibos** [comment]
Yay!!

**Comment by cfarm** [comment]
this has conflicts @virginiacc

**Comment by cfarm** [comment]
works as advertised. 👍  ready for merge once conflicts are fixed

**Comment by mthibos** [comment]
:+1: Looks great on build!  Let's deploy to production!

**Comment by mthibos** [comment]
This is deployed!  And it works!  :trophy:

**Pull request merged**
