### PR TITLE
Form explainer content-review-on-content-server fixes

### PR DESCRIPTION
**Pull request by stephanieosan**
### Changes
* Made all the links in the form explainers relative so that we can test askcfpb questions on content
* Commented out links that aren't ready for prime time yet
* Added descriptions for the two sad boxes that previously didn't have descriptions
* Fixed various punctuation oversights
* Corrected a link

### Review
@virginiacc or @amymok or @cfarm or @fna 
also tagging @mthibos so she stays in the loop :)

### CODE REVIEW

**Comment by mthibos** [comment]
Huzzah!! @stephanieosan is my favorite person ever!  :dancer: :rocket: :sparkles: :icecream:

**Comment by virginiacc** [comment]
@stephanieosan This looks great! :+1:  

My only question is, it looks like there are still a few absolute 'ask cfpb' links on `loan-estimate-1.html`. Do these need to be relative?

**Comment by huetingj** [comment]
:star:

**Comment by stephanieosan** [comment]
@virginiacc yessss. Thanks for finding those. Taking care of them now.

**Comment by stephanieosan** [comment]
Okay, those should be fixed and relative now! @virginiacc

**Comment by virginiacc** [comment]
:+1: :sparkles:  :shipit:

**Comment by cfarm** [comment]
:dancers: :cactus:

**Pull request merged**
