### PR TITLE
Updated copy and links on the landing page

### PR DESCRIPTION
**Pull request by stephanieosan**
#### Additions
* New content from Megan
* Added link to the Monthly Payment Worksheet

#### Screenshots
screen shot 2015-06-15 at 5 58 54 pm
screen shot 2015-06-15 at 5 58 59 pm

#### Review
@mthibos or @huetingj for content
@cfarm or @virginiacc or @amymok to make sure I didn't break anything

### CODE REVIEW

**Comment by mthibos** [comment]
:+1:  Looks good to me!!

**Comment by stephanieosan** [comment]
@cfarm or @virginiacc are there browser tests I need to update or add to reflect the new links?

**Comment by cfarm** [comment]
We don't have browser tests for the "Key tools" links yet. We should just create a new story for that - it's not a huge priority but we could do the 404 tests on those.

**Comment by huetingj** [comment]
:+1:

**Comment by sonnakim** [comment]
Should we add an icon for PDF links? It would be a nice cue for users who click on those "Guide to Closing Forms" and "Monthly Payment Worksheet" links.

image

**Comment by cfarm** [comment]
Yes to PDF icons! We should also make sure the icons are accessible

**Comment by stephanieosan** [comment]
Agreed :+1: We even have a more PDF-like icon that has the letters "PDF" in the little document instead of the lines of text. I can add PDF icons in when I update the sidebar of the landing page today or tomorrow.

**Comment by sonnakim** [comment]
:+1: Sounds good!

**Comment by Scotchester** [comment]
I thought we were moving away from the PDF icon because we felt it unreadable at typical inline-with-link sizes?

**Comment by stephanieosan** [comment]
I thought we were going to replace it in the minicon font with a little document without letters. Do you have that design manual issue number handy?

**Comment by Scotchester** [comment]
I couldn't locate it in Design Manual issues. Not sure that the discussion happened there.

**Comment by stephanieosan** [comment]
Cool. We're going with the download icon.

**Pull request merged**
