### PR TITLE
Generate code coverage reports

### PR DESCRIPTION
**Pull request by contolini**
This replaces the `mochaTest` grunt task with `mocha_istanbul` to track code coverage. Coverage reports are output to `test/coverage` and sent to [coveralls.io](https://coveralls.io/r/cfpb/owning-a-home). A coverage badge has been added to the README.

### CODE REVIEW

**Comment by ascott1** [comment]
ohhhhh, this is exciting

**Comment by mthibos** [comment]
@ascott1  What's a code coverage report?  I'm excited too, just want to know what about!  :grinning:

**Comment by stephanieosan** [comment]
Test coverage?

**Comment by contolini** [comment]
@stephanieosan Bingo. It's called code coverage instead of test coverage because you're covering the code in tests.

It's good practice to write automated tests that verify your code works as expected (and that it doesn't break as updates are made down the road). As a codebase grows, it can be hard to keep track of which parts of the application are *covered* by tests and which are not.

Code coverage tools tell you how much of your code is covered by tests. They generate reports that tell you "Hey! Function ABC and XYZ don't have any tests written for them." They'll also tell you the percentage of your code that is covered by tests. e.g. If you update the application and your code coverage drops from 100% to 85%, it means you failed to write proper tests for that new code.

**Comment by stephanieosan** [comment]
I love this!

**Pull request merged**
