### PR TITLE
pin the long term comparison to 30 years for ARM loans

### PR DESCRIPTION
**Pull request by ascott1**
selfie-0

### CODE REVIEW

**Comment by ascott1** [comment]
Worth noting: I'm  having trouble running the api locally, so this was written in *theory*, but I'm confident it'll work as needed.

**Comment by stephanieosan** [comment]
@akiany Can you review and merge this? @wernerc is out sick today.

**Comment by ascott1** [comment]
@akiny hold off. I'm going to make another improvement...

**Comment by ascott1** [comment]
Ok @akiany this is good to go.

**Comment by contolini** [comment]
Simple and sweet.

**Comment by akiany** [comment]
@contolini Thanks for merging it.

**Comment by mthibos** [comment]
@contolini .............. we miss you.............. you better come to our launch parties!!

**Comment by contolini** [comment]
:heart: :purple_heart: :green_heart: :blue_heart: 

Oh, I'll be there.

**Pull request merged**
