### PR TITLE
updating to the latest version of the selenium library

### PR DESCRIPTION
**Pull request by OrlandoSoto**
from 2.40 to 2.45

### CODE REVIEW

**Comment by OrlandoSoto** [comment]
@cfarm I have no idea why Travis failed,,

**Comment by OrlandoSoto** [comment]
hmmm I don't get it 
Running "browserify:tests" (browserify) task
>> Error: Cannot find module './state' from '/home/travis/build/cfpb/owning-a-home/node_modules/jsdom/node_modules/acorn-globals/node_modules/acorn/dist'
Warning: Error running grunt-browserify. Use --force to continue.

**Comment by cfarm** [comment]
Travis is currently unreliable due to a dependency bug

**Comment by cfarm** [comment]
Tested locally and the link passes :+1:

**Pull request merged**
