### PR TITLE
User testing fixes

### PR DESCRIPTION
**Pull request by virginiacc**
### Changes
- Remove links from tooltips
- Temporarily remove flush left styling from input table. This looked broken in the user testing browser. I'll work on fixing it in a subsequent pull request, today if possible.

### Additions
- Add credit score scenario. The data was all there in the related GH issue, so I added the full scenario... I could add inactivated entries in the dropdown for the other scenarios too.

### Screenshots

Credit score scenario & input table flush left style change:

screen shot 2015-06-18 at 1 29 14 pm

Links removed from tooltips:

screen shot 2015-06-18 at 1 30 21 pm

### Review
@cfarm @huetingj  @stephanieosan @sonnakim @mthibos

### CODE REVIEW

**Comment by cfarm** [comment]
Code looks good and I tried out the front end locally and things are workin' well. 

@stephanieosan  or @sonnakim will have to look before we merge

**Comment by stephanieosan** [comment]
This looks good to me! We're between tests for the next half hour, so it might be a good window to merge.

**Comment by stephanieosan** [comment]
Also, I'm sort of preferring the not flushed left. Maybe we should just keep it like this, and then you won't have to do work to fix it in other browsers?

**Comment by huetingj** [comment]
agreed... thank you!

**Pull request merged**
