### PR TITLE
Adding Planning for Retirement to main nav

### PR DESCRIPTION
**Pull request by Scotchester**
Should not deploy to production until 11/12 at 9:00 am EST.

### CODE REVIEW

**Comment by cfarm** [comment]
@virginiacc any complications with this release plan considering we have monthly-payment-worksheet in master? I would think it's ok so long as it's not been deployed via the grunt task yet.

**Comment by Scotchester** [comment]
Oh, sorry I forgot to do this already, but I was going to file a new PR that doesn't put this into `master`, following our conversation yesterday, @cfarm. But if you think it's okay this way, let me know.

**Comment by virginiacc** [comment]
@cfarm Hmm, good question. It's possible the worksheet will be ready to release on 11/12, but if not we should still be able to deploy from master since we're using that grunt task as a feature toggle. We'd probably want to comment out the worksheet js file in the browserify build task, though. 

We also need to specify a [version for the jquery sticky plugin](https://github.com/cfpb/owning-a-home/pull/647) next time we release to avoid breaking the form explainers, so we'd want to make that change in the release branch if we don't deploy from master.

**Comment by Scotchester** [comment]
Ok, then, if this is all good, merge when ready and we'll get it on Build and Content!

**Comment by Scotchester** [comment]
Friendly reminder, @cfarm and @virginiacc :)

**Comment by virginiacc** [comment]
Looks good! :+1:  Thanks, @Scotchester!

**Pull request merged**
