### PR TITLE
Loan comparison expandables

### PR DESCRIPTION
**Pull request by cfarm**
This PR is the small screen functionality for the Total Costs to Close expandable. I want to get this math reviewed by @mthibos on master ASAP. I'll work on the other expandables in subsequent branches.

## Added
* cf-expandables dependency in loan-comparison.js
* Markup for the "Total Costs to Close" expandable
* mobile-first CSS for the expandables for small screens only right now (<600px wide)
* JS to calculate the amounts for each line in the Total Costs to Close expandable

## Review
* @virginiacc 
* @stephanieosan 
* @mthibos

### Loans A and B, now with down payment!
screen shot 2015-03-10 at 4 17 37 pm

### CODE REVIEW

**Comment by mthibos** [comment]
Oh yay!  

Looks like the down payment amount is missing.  

And how do I look at the math itself?  I'll need some step-by-step instructions on where to look.  :)

**Comment by cfarm** [comment]
@mthibos I since added in the down payment amount to the total closing costs. There's not a row in the design for it though, if that's what you meant.

Line 63 through 91 in this file has the new placeholder values: https://github.com/cfarm/owning-a-home/blob/loan-comparison-expandables/src/static/js/modules/formalize.js#L63

And this section (line 93-102) adds them together: https://github.com/cfarm/owning-a-home/blob/loan-comparison-expandables/src/static/js/modules/formalize.js#L93

**Comment by mthibos** [comment]
@cfarm   I will look at the code, but there is supposed to be a line in the design for down payment.  Like this:

image

**Comment by cfarm** [comment]
Thanks for catching that. I just spotted it in the large screen design, will add in today!

**Comment by cfarm** [comment]
Closing since this work is being reviewed in #383

**Pull request closed without merging**
