### PR TITLE
Change to cfgov-refresh header and footer

### PR DESCRIPTION
**Pull request by Scotchester**
Overall, things look pretty good, but someone who knows OAH better needs to test this to make sure that the header and footer styles aren't breaking anything major.

Notably, Explore Interest Rates looks a little busted. Not sure if that's just a local testing issue.

**Review:**
- @cfarm
- @virginiacc
- @ascott1
- @contolini

/cc @rosskarchner

### CODE REVIEW

**Comment by Scotchester** [comment]
Force-pushed an update that should hopefully fix the build/test issues. C'mon, Travis, don't fail me now!

**Comment by Scotchester** [comment]
PASSSSED! Anyone want to test, or are we just going for it? :)

**Comment by jimmynotjim** [comment]
Testing now

**Comment by jimmynotjim** [comment]
Looks good! Nice work all around

**Comment by rosskarchner** [comment]
works for me! :+1:

**Comment by contolini** [comment]
tobias-amazing-grace

**Comment by Scotchester** [comment]
Huzzah! :shipit:

**Pull request merged**
