### PR TITLE
Closing checklist pdf

### PR DESCRIPTION
**Pull request by stephanieosan**
#### Changes
* Changed the words "30 years" to "many years" in the closing checklist pdf

#### Screenshot
screen shot 2015-06-25 at 12 24 30 pm

#### Review
@fna for making sure I didn't mess it up
@mthibos for content

### CODE REVIEW

**Comment by amymok** [comment]
Travis build failed because of this commit https://github.com/amymok/owning-a-home/commit/35746b43b622b5e38ae4ab01f0d93b3a45b8f1f4

As noted, all tests passed.

Everything should be fine after https://github.com/cfpb/owning-a-home/pull/490 is merged in.

**Comment by stephanieosan** [comment]
Hey, I'm making accessibility updates to this PDF (eventually). We might as well wait and not merge this.

**Comment by cfarm** [comment]
I'm going to close this PR, you can still make changes to your branch and reopen it when you're ready, @stephanieosan

**Comment by stephanieosan** [comment]
:+1:

**Pull request closed without merging**
