### PR TITLE
Add 2x2 layout for brand footer in 600-900px screen range

### PR DESCRIPTION
**Pull request by virginiacc**
Update brand footer layout in med screen range

## Additions

- `.grid_column(6)` layout in `@bp-sm` range & associated padding updates

## Changes
- fix positioning of footer on `/loan-options`
- fix some tags on `/loan-options`

## Testing

- Check out branch
- Run `grunt`
- Navigate to [/loan-options](http://localhost:8000/owning-a-home/loan-options/) and verify brand footer placement & layout across screen sizes

## Review

- @sonnakim 
- @huetingj 

## Screenshots

900px+:

screen shot 2016-11-21 at 10 00 49 am

600-899px:

screen shot 2016-11-21 at 10 01 08 am

< 600px:

screen shot 2016-11-21 at 10 01 22 am

## Notes
- Should the icons be centered in the 600-900px range?
- Should the desktop breakpoint be greater than 900px? We might want to tweak it when the email signup is added.

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices 
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by sonnakim** [comment]
@virginiacc I think the mobile implementation looks great! For the 600-899px implementation, would it be possible to add some left padding to the description and link text, so that they don't look quite so left aligned compared to the illustration?

**Comment by huetingj** [comment]
Or starting at 899px and continuing down to the smallest mobile point, could we just have the illustrations left aligned instead of centered?

**Comment by huetingj** [comment]
Hmm. Maybe? (Regarding breaking before 900px) Is the first screenshot above at 900px? It looks fine to me right now, though I guess a tad squishy. And yah perhaps it will appear too tight when the email signup language is added in. Hmmmmm. Maybe we leave for now and relook when the signup is added?

**Comment by virginiacc** [comment]
@sonnakim @huetingj 

Here's the 2x2 layout with left alignment:

screen shot 2016-11-21 at 10 20 27 pm


And a couple variations on shifting the image/text left of center:
screen shot 2016-11-21 at 10 24 40 pm

screen shot 2016-11-21 at 10 28 24 pm

screen shot 2016-11-21 at 10 30 26 pm


And here's the desktop layout at 900px with the email signup:

screen shot 2016-11-21 at 10 39 50 pm

It is a bit narrow, but maybe not too bad?

**Comment by sonnakim** [comment]
I'll defer to what @huetingj thinks! 

@virginiacc Just a placement note — on http://build.consumerfinance.gov/owning-a-home/loan-options/ , just need to swap the positions of the feedback module and footer, so that the latter sits right on top of the cf.gov footer. 

Also noticing an issue on the loan estimate and closing disclosure pages, which probably requires a separate PR? The form sometimes sticks in place, so that, the footer illustrations and copy bleed into the form itself: 
image

**Comment by mthibos** [comment]
@sonnakim   gah!  :scream:  good catch on that ugly footer javascript/whatever.

**Comment by sonnakim** [comment]
@mthibos i can't replicate that error consistently, so it took a few tries to capture!

**Comment by huetingj** [comment]
Let's go with left-aligned! I'm debating with the email signup... Will ask you a question in scrum, and we can make a decision and close this out.

**Comment by virginiacc** [comment]
@huetingj @sonnakim Just updated the footer so it's left aligned in the med range & desktop layout starts at 1000px. I'll push it to build and we can decide if we want to make any additional tweaks based on how it looks there.

**Comment by sonnakim** [comment]
@virginiacc sounds good!

**Comment by huetingj** [comment]
Thanks, @virginiacc! :) Everything looks great except I noticed one small thing: The "Get our closing checklist" and "Learn what to look for" links need the pdf download minicon and the end. 

screen shot 2016-11-23 at 8 45 32 am

**Pull request merged**
