### PR TITLE
Change name from How to take action to What to do now

### PR DESCRIPTION
**Pull request by kurtw**
This is a change to the processor due to the changes made in the metabox file in [this PR](https://github.cfpb.gov/OAH/wp-oah/pull/9).

@Scotchester Who is the dev on this project that usually reviews these things?

### CODE REVIEW

**Comment by mthibos** [comment]
@amymok @cfarm @virginiacc  
Who can merge this for @kurtw ?  We'd like it live by 1pm, please!

**Comment by Scotchester** [comment]
It would also require a change in the template to access the data with the new key. I'm going to hold on this one and your own for now and take @amymok's wp-oah update for simplicity. Once the template update is added here, we can accept the key change in wp-oah and run the DB query.

**Comment by cfarm** [comment]
@Scotchester is this what you needed? https://github.com/cfpb/owning-a-home/pull/468

**Comment by Scotchester** [comment]
Yep! Good call changing the mapping file, too. Closing this in favor of that.

**Pull request closed without merging**
