### PR TITLE
Loan comparison: mobile editing functionality & mobile inputs styling

### PR DESCRIPTION
**Pull request by virginiacc**
### Additions

- Loan name:
  - `setLoanName` function in loan store adds letter `name` property to loan for display on mobile 
  - Tests for `setLoanName` function

- Mobile editing functionality
  - adds `startMobileEditing` and `stopMobileEditing` functions in `App` component to store loan being edited in app state
  - adds mobile header in `LoanInputTable` component to identify loan being edited & `mobile-editing` classes to toggle display of loan inputs on mobile
  - adds 'save and close' buttons in `LoanInputTable` to stop mobile editing
  - adds edit buttons for each loan in `LoanOutputTableMobile` component to start mobile editing
  - hooks up name display & outputs for loan amount, summary, and points in  `LoanOutputTableMobile`
  - adds loan amount output for display on mobile in `LoanDownpaymentInput` component
  

- Mobile input styles
  - Adds identifying class to each `LoanInputTableRow` so they can be targeted on mobile
  - adds mobile-specific less for inputs

### Removals
- Removed interest rate update button & associated state

### Notes
- At the moment, the api is still being called on every change in mobile editing. These calls should just be made when exiting edit state, but I'm holding off on this until the output loading state is ready. I've revised the mobile editing task in the next sprint to cover this change.

### Preview
screen shot 2015-07-30 at 11 44 33 am

screen shot 2015-07-30 at 11 44 59 am

screen shot 2015-07-30 at 11 45 08 am

### Review
@cfarm @stephanieosan

### CODE REVIEW

**Comment by amymok** [comment]
@virginiacc Can you resolve the conflicts?  Then I can start reviewing

**Comment by virginiacc** [comment]
@amymok I think all the merge conflicts are fixed now...

**Comment by virginiacc** [comment]
@amymok The loan-comparison.js file is now commented out in the grunt browserify task, so you will need to uncomment the references to it locally in your Gruntfile to view these changes.

**Comment by amymok** [comment]
Looks great to me!

**Pull request merged**
