### PR TITLE
Added flags to first page of each of our two closing pdfs

### PR DESCRIPTION
**Pull request by stephanieosan**
### Additions
* Updated first page of each closing pdf to indicate they're consistent with current mortgage regulations. This is to avoid having to rethink how we link to these pdfs from the form landing pages for the August release.

### Screenshots
Closing Docs | Closing Checklist 
---- | ----
screen shot 2015-08-11 at 5 15 10 pm | screen shot 2015-08-11 at 5 26 55 pm

### Review
@cfarm or @virginiacc or @amymok or @fna 
Preferably to be reviewed today, so that this can go to content with the rest of the release tomorrow morning.

cc: @mthibos

### CODE REVIEW

**Comment by stephanieosan** [comment]
Oh, hold on. I made a copy mistake.

**Comment by stephanieosan** [comment]
Now it's ready!!! :boom:

**Comment by mthibos** [comment]
@sosan you are using the same disclaimer for both pdfs. The checklist should have checklist specific language.

**Comment by stephanieosan** [comment]
Yes, that was the copy mistake I was referencing. It should be fixed now.

**Comment by mthibos** [comment]
I can't figure out how to verify the fix with my limited GH powers, but I am willing to trust you.  :grinning:

**Comment by cfarm** [comment]
@mthibos click the "Files changed" tab at the top of the page and then click "View" for each pdf file listed. it will be really slow if your internet is bad like mine but eventually will load the actual PDF.

**Comment by mthibos** [comment]
@cfarm   I tried that, but somehow it didn't work the first time.  Worked this time, and the file looks good to me!  :boom:

**Comment by stephanieosan** [comment]
Huzzah!

**Pull request merged**
