### PR TITLE
Form Explainer pagination

### PR DESCRIPTION
**Pull request by virginiacc**
### Changes
- Removes bottom pagination
- Changes current page tracking in form explainer code & removes associated test

### Additions
- Adds top pagination & forward/back buttons on form image

### Preview

screen shot 2015-07-28 at 3 08 34 am

### Review
@cfarm @stephanieosan

### CODE REVIEW

**Comment by stephanieosan** [comment]
Overall this looks good! 

I have one small request: could the page numbers that are clickable have underlines a-la our link style? So, in this particular screenshot, 2 and 3 would have underlines but 1 wouldn't.

**Comment by virginiacc** [comment]
@stephanieosan I just added the underlines for desktop:

screen shot 2015-07-28 at 11 26 49 am

**Comment by stephanieosan** [comment]
:+1:

**Comment by cfarm** [comment]
The only issue I see is some weird small spacing when the screen is narrow enough for the page numbers to wrap:

screen shot 2015-07-29 at 3 01 17 pm

But I think this is good to go for now.

**Comment by stephanieosan** [comment]
Just wanted to say the new pagination is really nice!

**Pull request merged**
