### PR TITLE
Release journey

### PR DESCRIPTION
**Pull request by virginiacc**
Reverses #618. Shows all links to the journey.

## Removals
- revert changes to `related_links.html` code so that so bottom nav appears
- add journey tests back to `navigation.feature`
- uncomment `process` links in `loan-estimate/loan-estimate-2.html`, `loan-estimate/loan-estimate-3.html`, and `mortgage-estimate/index.html`

## Testing

- check out branch locally
- run `sh frontendbuild.sh`
- run `grunt deploy`
- view front end and test that:
  - journey landing page is the homepage:
    - [http://localhost:7000/process/](http://localhost:7000/process)
    
  - the following pages have bottom nav with journey links:
    - [http://localhost:7000/explore-rates/](http://localhost:7000/explore-rates/)
    - [http://localhost:7000/loan-options/](http://localhost:7000/loan-options/)
    - [http://localhost:7000/loan-estimate/](http://localhost:7000/loan-estimate/)
    - [http://localhost:7000/closing-disclosure/](http://localhost:7000/closing-disclosure/)
    
  - the `Learn how to shop for multiple Loan Estimates` link to the journey is active on mortgage estimate page:
    - [http://localhost:7000/mortgage-estimate/](http://localhost:7000/mortgage-estimate/)

  - the journey links are active on [http://localhost:7000/loan-estimate/](http://localhost:7000/loan-estimate/)
    * [x] Check details, page 2, `Review the Services You can shop for`
    * [x] Check details, page 2, `Is the homeowner's insurance premium accurate`
    * [x] Check details, page 3, `Use the comparisons section...` (2 links)
  
- Confirm the follow features are *not* built:
  - [http://localhost:7000/loan-comparison/](http://localhost:7000/loan-comparison/)
  - [http://localhost:7000/prepare-worksheets/](http://localhost:7000/prepare-worksheets/)

- Check that smoke tests for journey links on the landing page are back 
  
## Notes
  - Still need to fix the `know before you owe` browser test on landing page

## Review

- @cfarm or @amymok 

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices 
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by cfarm** [comment]
Regarding: "Still need to fix the know before you owe browser test on landing page" - isn't that issue just temporary until the redirect is in place? If so we can ignore it.

**Comment by cfarm** [comment]
@virginiacc I'm comparing this against the launch checklist from #618, the only thing missing is 'update version number on css & js links in base.html'

**Comment by mthibos** [comment]
as of 6pm today., /knowbeforeyouowe/ will redirect to /know-before-you-owe/

Or so I believe.  @Scotchester

**Comment by Scotchester** [comment]
@mthibos That is correct.

**Comment by virginiacc** [comment]
@cfarm Oh, good catch -- I did update the version numbers, but didn't add that to the testing checklist.

Also, I just updated the kbyo browser test so it passes for me against build...

**Comment by cfarm** [comment]
Ok we're good to go!

**Pull request merged**
