### PR TITLE
Add journey jump links

### PR DESCRIPTION
**Pull request by fna**

### CODE REVIEW

**Comment by fna** [comment]
this, GHE/OAH/wp-oah/pull/10, will have to be merged too.

ES content will need to be reindexed in order to see it working

**Comment by stephanieosan** [comment]
Who should review this— @amymok ?

**Comment by fna** [comment]
@stephanieosan she can

**Comment by amymok** [comment]
@fna How do I test this?

**Comment by fna** [comment]
I used UnityBox to run Wordpress and loaded the latest data dump there, login into WP admin and edit existing step, add Collapse link field, then re-indexed ES from it ``WORDPRESS=http://localhost:8080 sheer index --reindex`` after run OaH in sheer and go to process/XXXX (depends on where the step you changed is located) and process/XXXX#created-collapse-link should take you to that section and expand it

**Comment by amymok** [comment]
Looks good!

**Pull request merged**
