### PR TITLE
Journey sources link

### PR DESCRIPTION
**Pull request by cfarm**
Adds Sources link to Journey phase pages after the Action Steps section. 

## Additions

- link markup to match the width of the action steps container
- `block__bg-small` class to reduce padding of the default `block__bg` element styling

## Review

- @amymok  
- @huetingj 

### Small screen on Prepare page
screen shot 2015-08-13 at 11 46 05 am

### Large screen on Prepare page
screen shot 2015-08-13 at 11 46 12 am

### Large screen on Close page
screen shot 2015-08-13 at 11 46 22 am

## Todos

- contribute `block__bg-small` to cf-layout and update our CF components to v1.0
- browser QA 

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Visually tested in supported browsers and devices 

Windows 7
* [x] IE 11
* [x] IE 10
* [x] IE 9
* [x] IE 8
* [ ] latest Chrome
* [ ] latest Firefox

Mac
* [ ] latest Chrome
* [ ] latest Firefox
* [ ] latest Safari

Mobile
* [x] latest iPhone
* [x] latest iPad
* [ ] latest Android
* [ ] latest BlackBerry

### CODE REVIEW

**Comment by amymok** [comment]
Looks good to me, waiting for designers to comment before merging.
@huetingj @stephanieosan

**Comment by mthibos** [comment]
I'm certain I should have commented on this before, but better now than later, right?  :grimacing: 

I'm not 100% loving this copy.  I think it implies something broader than what we're offering.  Will put the thinking cap and post a recommendation back here in a few minutes.

**Comment by mthibos** [comment]
How's this:

Visit our <link> sources page </link> to learn more about the facts and numbers we reference.

**Comment by huetingj** [comment]
Design looks great! Thanks!

**Comment by stephanieosan** [comment]
Sorry, this is super nit-picky, but could we get 60 px of space below the grey link box on the small screen too? That way the bottom nav feels more separate. It looks like it's 30 right now.

screen shot 2015-08-13 at 11 46 05 am

**Comment by cfarm** [comment]
Updated the copy and padding:

### Small screen:
screen shot 2015-08-14 at 10 34 30 am

### Large on Prepare step:
screen shot 2015-08-14 at 10 42 25 am

### Large on Close step:
screen shot 2015-08-14 at 10 42 19 am


The padding updates also make the whitespace between the Action Steps and the bottom nav consistently 60 pixels across the pages. Previously the whitespace on pages with the green 'tools for this phase' box was much larger.

**Comment by mthibos** [comment]
looks good to me!  FYI if it matters, we are going to have the green tools sidebar on all the phases, I just haven't implemented that yet in WP.

**Comment by huetingj** [comment]
:+1: beautiful

**Pull request merged**
