### PR TITLE
Shrinkwrap node deps

### PR DESCRIPTION
**Pull request by contolini**
This locks down all node dependencies so that we know exactly what is being installed and can circumvent the Travis/acorn bug.

See: https://docs.npmjs.com/cli/shrinkwrap

### CODE REVIEW

**Comment by cfarm** [comment]
wowsers

so how do we keep this updated? is it automated?

**Comment by contolini** [comment]
Yeah, whenever you add a new dep you run `npm shrinkwrap`. https://docs.npmjs.com/cli/shrinkwrap#building-shrinkwrapped-packages

**Comment by cfarm** [comment]
Should we add anything to the readme for this?

**Comment by contolini** [comment]
Good call! Added.

**Comment by cfarm** [comment]
Sweet :+1:

**Pull request merged**
