### PR TITLE
Form explainer test

### PR DESCRIPTION
**Pull request by himedlooff**
Here's some form explainer code that I want to test on the dev server.

selfie-0

### CODE REVIEW

**Comment by ascott1** [comment]
:+1: Looks good.

**Comment by ascott1** [comment]
selfie-1

**Comment by mthibos** [comment]
Exciting, @himedlooff !

Does this mean that there is a prototype live on build that we can play around with?  :rocket:

**Comment by himedlooff** [comment]
@mthibos, once this is merged it should fire off a chain of events that will put this on build. If not I'll have to do some asking around.

**Comment by mthibos** [comment]
@himedlooff Couldn't find anything, what's the URL?

**Comment by himedlooff** [comment]
@ascott1, @contolini, not seeing this on build. Do I need to add something to the Gruntfile to get it to show up there?

**Comment by ascott1** [comment]
Hmm, I thought build ran the default grunt tasks. @fna would know more.

**Comment by himedlooff** [comment]
Got some emails about failing browser tests, that might be the issue.

**Comment by ascott1** [comment]
Ahh, it probably is.

**Comment by himedlooff** [comment]
@OrlandoSoto, is there anything that a new page should watch out for regarding browser tests? Not sure why adding a new page would cause them to fail.

**Comment by OrlandoSoto** [comment]
@himedlooff hmmm browser tests should not fail when a new page is added,, are you testing from Jenkins? forward me the test logs so I can see why it's failing

**Comment by himedlooff** [comment]
@OrlandoSoto, emailed you the failing test notifications I received.

**Comment by OrlandoSoto** [comment]
on further investigation, it looks like our Sauce Tunnel in Jenkins stopped running for a few hours on Saturday which caused the Jenkins jobs to fail.
This is a known issue where the Sauce Labs tunnel becomes stale, we have a daily job in Jenkins that refreshes the tunnel everyday to work around this problem.
Subsequent browser tests executed successfully in Jenkins on Sunday

**Pull request merged**
