### PR TITLE
Credit score bug fix

### PR DESCRIPTION
**Pull request by virginiacc**
Fixes bug where credit score warning goes away when any input is changed (more info [here](https://github.cfpb.gov/OAH/OAH-notes/issues/443))

## Changes

- Only remove credit score warning if credit score is changed

## Testing

- Check out branch
- Run `./frontendbuild.sh`
- Navigate to [explore rates page](http://localhost:7000/explore-rates/) and move credit score slider to its lowest setting (600-619). Check that warning appears.
- Change another input's value (state, house price, etc). Check that warning still appears.
- Change credit score to higher value. Check that warning disappears.

## Review

- @cfarm or @fna 

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices 
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by cfarm** [comment]
this is good to go! 👍

**Comment by mthibos** [comment]
Yay!  :+1:

**Comment by mthibos** [comment]
So does that mean this is on build now?

**Comment by mthibos** [comment]
Reviewed on build, looks great.  Let's push it live!  :rocket:

**Pull request merged**
