### PR TITLE
Form explainer final clearance content

### PR DESCRIPTION
**Pull request by stephanieosan**
### Additions
* Lots of content updates on every page of both forms 
* Updated image for pg 2 of Closing Disclosure "Services borrower didn't shop for..."
* Added em dash to intro paragraph of Closing Disclosure

### Notes
* That image doesn't work locally for me either, but it is currently working on build. I don't know what's up with that. Maybe we should not worry about it not showing up locally and push to build to see if it works there or not? Plz advise.
* There are a handful of links still missing. I will be adding those later, still waiting on them.

### Review
@cfarm or @virginiacc or @amymok or @fna 
Megan or Erica will need to review this content in great detail once it's up on build.

### CODE REVIEW

**Comment by stephanieosan** [comment]
@mthibos Just added the Adjustable rate loan estimate sample PDF and corresponding link to this PR.

**Comment by virginiacc** [comment]
@stephanieosan Looks good! :+1:  I didn't review the content in too much detail since that will happen once it's on build, but the changes look good & everything's working locally (except the new pdf link, since it's not on cf.gov yet).

For the `services-not-shopped-for-highlight` image (or any resource in the `static` folder), we can use the template's `url_for` helper function & it'll generate urls that work in the current environment, locally or on build/production:

`"img": url_for('static', filename='img/services-not-shopped-for-highlight.png')`

**Comment by stephanieosan** [comment]
Awesome—thanks, @virginiacc! The image is working locally for me, now!

**Comment by stephanieosan** [comment]
Should I change the new PDF link to be relative, so that it will work on build (since the PDF is stored in our repo)?

**Comment by stephanieosan** [comment]
I updated the PDF link, you should be able to see the PDF on build now, too!

**Comment by virginiacc** [comment]
@stephanieosan I think this is ready to go! :shipit:

**Pull request merged**
