### PR TITLE
Print styles

### PR DESCRIPTION
**Pull request by cfarm**
Basic print styles:

* Uses [print mixin from Capital Framework](https://github.com/cfpb/cfgov-refresh/issues/248)
* Includes HTML5 Boilerplate print styles
* Removes background colors and images
* Changes text, link, border colors to grayscale for faster/cheaper printing
* Adds link href after link elements

Screenshots of the OaH landing page with these styles applied. Note that layout remains fluid and unchanged from the default responsive styling:

screen shot 2015-02-17 at 5 37 13 pm
screen shot 2015-02-17 at 5 37 23 pm

I'd love feedback from designers on how to improve future iterations of these styles.

### CODE REVIEW

**Comment by stephanieosan** [comment]
Oooh, this is exciting! Looking forward to playing around with it on different pages.

Also, no gif no merge, thems the rules.
selfie-0

**Comment by cfarm** [comment]
selfie-1

**Comment by cfarm** [comment]
Here's the Understanding Loan Options page:

screen shot 2015-02-17 at 7 02 23 pm
screen shot 2015-02-17 at 7 02 32 pm

**Comment by ascott1** [comment]
selfie-0

**Comment by cfarm** [comment]
@ascott1 DID YOU ACTUALLY PRINT IT?

**Comment by virginiacc** [comment]
Lovely!  :+1:

**Pull request merged**
