### PR TITLE
change key to what_to_do_now

### PR DESCRIPTION
**Pull request by cfarm**
Fixed template keys for https://github.com/cfpb/owning-a-home/pull/468

@Scotchester @kurtw

### CODE REVIEW

**Comment by Scotchester** [comment]
Anyone understand why the Travis build failed?

**Comment by cfarm** [comment]
No idea. @contolini halp?

**Comment by contolini** [comment]
Looks like a `node-coveralls` [bug](https://github.com/cainus/node-coveralls/issues/80). Can't investigate right now but I shall later.

**Comment by cfarm** [comment]
@contolini we're planning to merge this tomorrow for a release next week, is it okay to ignore this coveralls bug?

**Comment by contolini** [comment]
'Tis fine -- the tests are passing. I'll keep this on my radar.

**Comment by contolini** [comment]
Ignore Travis -- everything is fine. See https://github.com/cfpb/owning-a-home/issues/481#issuecomment-113222853.

**Pull request merged**
