### PR TITLE
Worksheet priority buttons: mobile stacking 'n' more

### PR DESCRIPTION
**Pull request by cfarm**
## Additions
* Styles for btn__super and btn__secondary to match latest design
* Updated button colors for the priority buttons
* Stacked buttons + inputs for smaller screens < 600px wide, plus stacked design between 800-960px widths so that inputs are always legible.
* Stacked priority labeling above the priority buttons for the same breakpoints described above

#### Small screen ~320px width styles
screen shot 2015-02-23 at 11 28 10 am

#### Medium screen ~600px - unstacked
screen shot 2015-02-23 at 11 29 16 am

#### Mediumer screen ~800px - re-stacked
screen shot 2015-02-23 at 11 29 38 am

#### Large screen 920px+ - unstacked again.
screen shot 2015-02-23 at 11 31 17 am

#### Large screen with updated button styles.
screen shot 2015-02-23 at 1 18 46 pm

### CODE REVIEW

**Comment by cfarm** [comment]
## Review
* @huetingj 
* @virginiacc

**Comment by huetingj** [comment]
This looks awesome, @cfarm. Assuming the .subheading border color change to gray you made and referenced in #353 will apply to the borders on this page?

**Comment by cfarm** [comment]
@huetingj that was @virginiacc! and yes it should when all get merged.

**Comment by huetingj** [comment]
:+1: Thanks, @virginiacc!

**Pull request merged**
