### PR TITLE
Update check rates url to explore rates

### PR DESCRIPTION
**Pull request by fna**
Short description explaining the high-level reason for the pull request

## Additions

- 

## Removals

- 

## Changes

- change check-rates folder inside src dir to explore-rates, so sheer serves it from that URL

- change all check-rates links in code to explore-rates

- update browser test accordingly

## Testing

- js unittests work

## Review

- @amymok @virginiacc @cfarm 

## Todos

- 

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Passes all existing automated tests
* [x] Visually tested in supported browsers and devices (only Chrome)

### CODE REVIEW

**Comment by fna** [comment]
Oh, and I don't know about all the out-OaH content that has links to old check-rates

**Comment by cfarm** [comment]
@fna this branch has conflicts, once you fix those i can try it out locally.

**Comment by fna** [comment]
@cfarm try https://github.com/fna/owning-a-home/tree/change-check-rates-to-explore-rates. I'll create another PR if that works

**Comment by cfarm** [comment]
@fna yeah that one is good.

**Comment by fna** [comment]
Closing this one, new one is [here](https://github.com/cfpb/owning-a-home/pull/587)

**Pull request closed without merging**
